FROM golang:1.15 AS build

ENV CGO_ENABLED=0
ENV GO111MODULE=on
ENV GOOS=linux

WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go build -o ./bin/app ./cmd/frontend/...

FROM alpine:latest as run
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build /app/bin/app .
COPY --from=build /app/.env .
COPY --from=build /app/frontend/dist static

CMD ["./app"]