// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/smogger/service.go

// Package mock_smogger is a generated GoMock package.
package mock_smogger

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockApiClient is a mock of ApiClient interface
type MockApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockApiClientMockRecorder
}

// MockApiClientMockRecorder is the mock recorder for MockApiClient
type MockApiClientMockRecorder struct {
	mock *MockApiClient
}

// NewMockApiClient creates a new mock instance
func NewMockApiClient(ctrl *gomock.Controller) *MockApiClient {
	mock := &MockApiClient{ctrl: ctrl}
	mock.recorder = &MockApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockApiClient) EXPECT() *MockApiClientMockRecorder {
	return m.recorder
}

// Cities mocks base method
func (m *MockApiClient) Cities(country string, v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cities", country, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cities indicates an expected call of Cities
func (mr *MockApiClientMockRecorder) Cities(country, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cities", reflect.TypeOf((*MockApiClient)(nil).Cities), country, v)
}

// Measurements mocks base method
func (m *MockApiClient) Measurements(city string, dateFrom, dateTo time.Time, v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Measurements", city, dateFrom, dateTo, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Measurements indicates an expected call of Measurements
func (mr *MockApiClientMockRecorder) Measurements(city, dateFrom, dateTo, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Measurements", reflect.TypeOf((*MockApiClient)(nil).Measurements), city, dateFrom, dateTo, v)
}
